### ISSUE TITLE
Restructure plugin in conduit crd

### ISSUE THREAD

**Issue by lyuboxa** [ConduitIO/conduit-operator#42]
```yaml
plugin:
  name:
  version:
```

or 

```yaml
pluginName: ...
pluginVersion: ...
```

_Originally posted by @raulb in https://github.com/ConduitIO/conduit-operator/pull/40#discussion_r1804881099_
